ТЗ 13. Попытка 1
romaozna/java-shareit pull request #1
Opened 2023-03-20 20:17 UTC by romaozna

2023-03-21 20:01 UTC, Fleaman777 requested changes

2023-03-21 20:01 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    Status status;
поля должны быть private

2023-03-21 20:01 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse handleThrowable(final Throwable e) {
в принципе можно не писать этот хэндлер, т.к. спринг сам оберенет не отловленное исклбчение в 500 респонс

2023-03-21 20:01 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> getUserItems(@RequestHeader("X-Sharer-User-Id") Long userId) {
"X-Sharer-User-Id"  - можно было бы вынести в константу

2023-03-21 20:01 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/dao/ItemStorageImpl.java
> +                .stream()
values и stream можно было бы написать на одной строке, 
такая запись была бы чуть грамотней

2023-03-22 03:42 UTC, romaozna commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse handleThrowable(final Throwable e) {
заменю Throwable на Exception. Выполняю рекомендацию наставника Иванова, в вебинаре он сказал что если такого обработчика не будет, ошибок в логах на гите мы не увидим

2023-03-22 04:05 UTC, romaozna commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> getUserItems(@RequestHeader("X-Sharer-User-Id") Long userId) {
private final static я ее сделать не могу так как валидатор стиля не пропускает static и SCREAMING_SNAKE_CASE

2023-03-22 19:00 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public ErrorResponse handleThrowable(final Throwable e) {
ну да, хороший поинт

2023-03-22 19:02 UTC, Fleaman777 approved these changes

2023-03-23 06:13 UTC, merged