ТЗ 15. Попытка 1
romaozna/java-shareit pull request #3
Opened 2023-04-02 15:51 UTC by romaozna

2023-04-02 17:19 UTC, romaozna commented
Роман, тест на гите не хотел проходить, хотя у меня все хорошо проходило, из-за этого столько коммитов. Проблема видимо во времени сервера, так как прошел только когда букингам присвоил дальние даты.

2023-04-03 21:10 UTC, Fleaman777 requested changes

2023-04-03 21:10 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam(value = "from", required = false, defaultValue = "0") @Min(0) Integer from,
можно явно не указывать параметр name и value если их значения совпадают с названием аргумента в методе

2023-04-03 21:10 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/RequestController.java
> +    private final String userIdFromHeader = "X-Sharer-User-Id";
это поле больше похоже на константу, поэтому его можно назвать в верхнем регистре и сделать статичным

(если конечно чекер не будет ругаться, а то бывают проблемы)

2023-04-03 21:10 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/dao/RequestStorage.java
> +public interface RequestStorage extends JpaRepository<ItemRequest, Long> {
обычно подобного рода интерфейсы или классы называют не Storage, а Repository, по аналогии с интерфейсом JpaRepository

2023-04-03 21:10 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +            LocalDateTime.now().plusDays(1));
инициализацию различных полей, наподобие bookingInDto, можно было бы вынести в метод с аннотацией @BeforeEach или @BeforeAll 
там же, вынести LocalDateTime.now() в локальную переменную, что бы не дублировать ее получение

2023-04-03 21:10 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntegrationTest.java
> +    }
по хорошему, 
в тест методе должен проверятся какой-то один сценарий, 
т.е. 1 раз вызваться какой-то конкретный метод проверяемого сервиса, 
так тесты становятся более изолированными, более мелкими, а значит проще их понимать

2023-04-03 21:10 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +                        .param("text", "text")
какие-то общие стринговые значения можно выносить в константы, что бы не дублировать их написание

2023-04-03 21:10 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +    void addComment() {
лучше хоть немного, но делать имя тестого метода отличным от основного приложения, 
так при полнотекстовом поиске по всему репозиторию проще будет ориентироваться в методах 

самое просто, и ты уже это используешь, добавлять в название test, 
еще лучше писать при каких условиях выполняется тест 
...if....

2023-04-03 21:14 UTC, Fleaman777 commented
> Роман, тест на гите не хотел проходить, хотя у меня все хорошо проходило, из-за этого столько коммитов. Проблема видимо во времени сервера, так как прошел только когда букингам присвоил дальние даты.

окей, понял
не проблема, главное есть результат

но мини момен на будущее, лучше коммиты называть по-разному, хотя бы их порядковые номера )

2023-04-05 13:08 UTC, Fleaman777 approved these changes

2023-04-05 13:08 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +    }
👍

2023-04-05 16:25 UTC, merged