ТЗ 16. Попытка 1
romaozna/java-shareit pull request #4
Opened 2023-04-06 18:42 UTC by romaozna

2023-04-07 16:34 UTC, Fleaman777 requested changes

2023-04-07 16:34 UTC, Fleaman777 commented on gateway/Dockerfile
> +FROM amazoncorretto:11-alpine-jdk
хорошо, что указываешь конкретную версию имеджа, а не просто latest,
так безопасней, т.к. меньше шансов нарваться на версию базового имеджа, с которым текущая версия приложения не будет работать,

то же относится и к Docker-Compose

2023-04-07 16:34 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public static final String USER_ID_FROM_HEADER = "X-Sharer-User-Id";
статические поля должны идти перед обычными

2023-04-07 16:34 UTC, Fleaman777 commented on server/src/main/resources/application.properties
> +spring.datasource.username=${POSTGRES_USER}
здорово, правильная конструкция для просечивания энв переменных,
еще можно ее немного дополнить
spring.datasource.username=${POSTGRES_USER:root}

через двоеточие указывается значение, которое будет использоваться по умолчанию, если энв переменная не будет просечена

2023-04-07 18:15 UTC, romaozna commented on server/src/main/resources/application.properties
> +spring.datasource.username=${POSTGRES_USER}
о, спасиба)

2023-04-07 18:52 UTC, romaozna commented on server/src/main/resources/application.properties
> +spring.datasource.username=${POSTGRES_USER}
спасибо за такой отзыв в ревью, но честно говоря хочется сказать, что я это не специально) спринт такой странный, я вроде только начал, переносил логику в gateway, менял вызовы через клиент и тут раз и приложение готово. Минут за 10 написал докерфайл и композ. Ну и потом имел некоторые сложности на тестах на сервере как обычно. Не говорю что легко, просто неожиданный финал, даже встрадать не успел) или после 15ТЗ так кажется

2023-04-08 18:37 UTC, Fleaman777 commented on server/src/main/resources/application.properties
> +spring.datasource.username=${POSTGRES_USER}
супер, что так последние работы зашли, значит точно уже есть хороший скилл, 
что все идек как по маслу)
Молодец!)

2023-04-08 18:37 UTC, Fleaman777 approved these changes

2023-04-08 19:24 UTC, merged